[package]
name = "russh-extra"
description = "High-level async SSH APIs built on top of russh."
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["client", "known-hosts", "aws-lc-rs"]
_russh = ["dep:russh"]
agent = ["client"]
aws-lc-rs = ["_russh", "russh/aws-lc-rs"]
client = ["_russh"]
flate2 = ["_russh", "russh/flate2"]
known-hosts = ["_russh"]
ring = ["_russh", "russh/ring"]
rsa = ["_russh", "russh/rsa"]
serde = ["russh-extra-core/serde"]
server = ["_russh"]
sftp = ["client", "dep:async-trait"]
shell = ["client"]
tunnel = ["client", "server"]
full = ["client", "server", "shell", "tunnel", "known-hosts", "agent", "sftp", "aws-lc-rs", "flate2", "rsa"]

[dependencies]
async-trait = { workspace = true, optional = true }
base64.workspace = true
bytes.workspace = true
rand.workspace = true
russh = { workspace = true, optional = true }
russh-extra-core.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
rand.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
